# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: test
                        roles: ROLE_ADMIN
        our_db_provider:
            entity:
                class: AppBundle\Entity\Users
                property: email

        # créer un provider regroupant les autres providers
        all_providers:
            chain:
                providers: [ in_memory, our_db_provider ]

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        AppBundle\Entity\Users:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                username_parameter: email
                password_parameter: password

            logout:
                path: logout # url de logout
                target: home # page de destination apres logout

            provider: all_providers
            #form_login: ~
